blogProject/accounts/urls.py
from django.urls import path
from accounts import views

app_name = "accounts"

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),

] 

blogProject/blogProject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from blog import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),

    path('create/', views.create, name='create'),
    path('post_list/', views.post_list, name='post_list'),
    path('post_detail/<int:id>/', views.post_detail, name='post_detail'),
    path('update/<int:id>/', views.post_update, name='post_update'),
    path('delete/<int:id>/', views.post_delete, name='post_delete'),

    path('create_comment/<int:id>', views.create_comment, name='create_comment'),
    path('update_comment/<int:post_id>/<int:com_id>', views.update_comment, name='update_comment'),
    path('delete_comment/<int:post_id>/<int:com_id>', views.delete_comment, name='delete_comment'),

    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('authaccounts/', include('allauth.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blogProject/accounts/models.py
from django.db import models

# Create your models here.

blogProject/blog/models.py
from django.db import models
from django.contrib.auth.models import User

class Post(models.Model):
    title = models.CharField(verbose_name="제목", max_length=128)
    body = models.TextField(verbose_name="내용", default="")
    created_at = models.DateTimeField(verbose_name="작성일", auto_now_add=True)
    photo = models.ImageField(verbose_name="이미지", blank=True, null=True, upload_to='blog_photo')
    author = models.ForeignKey(User, on_delete=models.CASCADE, null=True)

    def __str__(self): 
        return self.title
    
class Comment(models.Model):
    comment = models.CharField(max_length=200)
    date = models.DateTimeField(auto_now_add=True)
    article = models.ForeignKey(Post, on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE, null=True)

    def __str__(self): 
        return self.comment

blogProject/blog/forms.py
from .models import Post, Comment
from django import forms

class PostModelForm(forms.ModelForm):
    class Meta: 
        model = Post
        fields = ['title', 'body', 'photo']


class CommentForm(forms.ModelForm): # 또다른 class로서 forms 안에 ModelForm을 상속받은 클래스를 하나 만들어줌
    class Meta: # Meta 클래스 하에, 어떤 모델을 기반으로 자동으로 form을 생성할 것인지 명시
        model = Comment 
        # 어떤 필드를 입력 받을지 써주기
        fields = ['comment']

blogProject/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib import auth
from django.contrib.auth.models import User

def signup(request):
    if request.method == "POST":
        if request.POST['password'] == request.POST['repeat']:
            new_user = User.objects.create_user(username=request.POST['username'], password=request.POST['password'])
            #로그인
            auth.login(request, new_user ,backend='django.contrib.auth.backends.ModelBackend')
            print('회원가입 성공')
            return redirect('home')
    return render(request, 'signup.html')

def login(request):
    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]
        user = auth.authenticate(request, username=username, password=password)

        if user is not None:
            auth.login(request, user, backend='django.contrib.auth.backends.ModelBackend')
            print('로그인 성공')
            return redirect('home')
        else: 
            return render(request, 'bad_login.html')
    else:
        return render(request, 'login.html')
    
def logout(request):
    auth.logout(request)
    return redirect('home')

blogProject/blog/views.py
from django.shortcuts import redirect, render, get_object_or_404
from django.core.paginator import Paginator
from .models import Post, Comment
from .forms import PostModelForm, CommentForm

def home(request):
    return render(request, 'index.html')


def create(request):
    if request.method == 'POST' or request.method == 'FILES': 
        # 입력 내용을 DB에 저장
        form = PostModelForm(request.POST, request.FILES) 
        if form.is_valid(): 
            # 유효하다면 저장하는 코드
            unfinished = form.save(commit=False)
            unfinished.author = request.user
            unfinished.save()
            return redirect('home') 
    else:
        form = PostModelForm() 
    return render(request, 'form_create.html', {'form':form})
   

def post_list(request):
    posts = Post.objects.all().order_by('-created_at')
    paginator = Paginator(posts, 5) # posts를 5개를 끊어서 home에서 보여주겠다
    pagnum = request.GET.get('page') # page number(몇 번째 바닥에 있는지)에 해당하는 숫자를 갖고 올 것임
    posts = paginator.get_page(pagnum) # pagnum번째 바닥에 해당하는 만큼 자른 객체가 posts에 담길 것이고 그걸 return으로 보여준다
    return render(request, 'post_list.html', {'posts':posts})


def post_detail(request, id):
    post = get_object_or_404(Post, pk=id)
    comment_form = CommentForm()
    context={
        'post':post,
        'comment_form' : comment_form
    }
    return render(request, 'post_detail.html', context)


def post_update(request, id):
    post = get_object_or_404(Post, pk=id)
    if request.method == 'POST' or request.method == 'FILES':
        form = PostModelForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            form.save()
            return redirect('post_list')
    else:
        form = PostModelForm(instance=post)
        return render(request, 'form_create.html', {'form':form, 'id':id})


def post_delete(request, id):
    post = Post.objects.get(pk=id)
    post.delete()
    return redirect('post_list')




def create_comment(request, id):
    filled_form = CommentForm(request.POST)

    if filled_form.is_valid():       
        finished_form = filled_form.save(commit=False)      
        finished_form.article = get_object_or_404(Post, pk=id)
        finished_form.author = request.user
        finished_form.save()
    return redirect('post_detail', id)


def update_comment(request, post_id, com_id):
    my_com = Comment.objects.get(id=com_id)
    comment_form = CommentForm(instance=my_com)
    if request.method == "POST":
        update_form = CommentForm(request.POST, instance=my_com)
        if update_form.is_valid():
            update_form.save()
            return redirect('post_detail', post_id)
    else:
        return render(request, 'comment_update.html', {'comment_form' : comment_form})
    

def delete_comment(request, post_id, com_id):
    my_com = Comment.objects.get(id=com_id)
    my_com.delete()

    return redirect('post_detail', post_id)

blogProject/accounts/templates/bad_login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>bad_login</title>
</head>
<body>
    존재하지 않는 회원입니다. 다시 로그인해주세요.
    <br/>
    <a href="{% url 'accounts:login' %}">다시 로그인하기</a>
</body>
</html>

blogProject/accounts/templates/login.html
{% load socialaccount %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
</head>
<body>
    <h1>로그인</h1>
    <form class="user" method="POST">
        {% csrf_token %}
        <div>
            <input type="text" id="username" name="username" placeholder="아이디를 입력해주세요.">
        </div>
        <div>
            <input type="password" id="password" name="password" placeholder="비밀번호를 입력해주세요.">
        </div>
        <input type="submit" value="로그인">
        <hr>
        <a href="{% provider_login_url 'google' %}">
            <i>구글 로그인</i>
        </a>
        </a><br>
    </form>
</body>
</html>

blogProject/accounts/templates/signup.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>회원가입</title>
</head>

<body>
    <h1>회원가입</h1>
    <form class="user" method="POST">
        {% csrf_token %}
        <div>
            <input type="text" name="username" placeholder="Enter Your ID">
        </div>
        <div>
            <div>
                <input type="password" name="password" placeholder="Password">
            </div>
            <div>
                <input type="password" name="repeat" placeholder="Repeat Password">
            </div>
            <div>
                <input type="text" name="last-name" placeholder="last-name">
            </div>
            <div>
                <input type="text" name="first-name" placeholder="first-name">
            </div>
        </div>
        <br><hr>
        <input type="submit" value="가입하기">
    </form>
</body>

</html>

blogProject/blog/templates/comment_update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form action="" method="POST">
        {% csrf_token %}
        {{comment_form.as_p}}
        <input type="submit" value="수정하기">
    </form>   
</body>
</html>

blogProject/blog/templates/form_create.html
<h1>Model form을 이용한 새 글 작성 페이지</h1>
<form action="" method="POST" enctype="multipart/form-data"> <!-- 파일 업로드를 하게 된다면 enctype을 지정해줘야 한다 -->
    {% csrf_token %}
    <div>
        <form action="" method="POST">
            {% csrf_token %}
            <table>
                {{ form.as_table }} <!-- 세번째 인자로 넘겨준 데이터 -->
                <!-- .as_p 는 p 태그가 감싸진 것처럼 해줌 / .as_ul은 ul 태그가 감싸진 것처럼 보임 -->
            </table>
            <input type="submit" value="새 글 작성하기">
        </form>      
    </div> <br>
</form>

blogProject/blog/templates/index.html
{% if user.is_authenticated %}
<a href="{% url 'accounts:logout' %}">{{ user.username }}님 로그아웃</a>
{% else %}
<a href="{% url 'accounts:signup' %}">회원가입</a>
<a href="{% url 'accounts:login' %}">로그인</a>
{% endif %}
<br><br>
<a href="{% url 'create' %}">django model form을 이용한 새 글 작성</a>
<br><br>
<a href="{% url 'post_list' %}">멋사 블로그 목록</a>

blogProject/blog/templates/post_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h2>제목: {{post.title}} </h2>
    <h4>작성 시간: {{post.created_at}} </h4>
    <h4>작성자: {{ post.author }}</h4>
    <hr>
    <h3>사진</h3>
    {% if post.photo %}
        <img src = "{{ post.photo.url }}" alt="" height="300">
    {% endif %}
    <p> {{post.body}} </p>
    {% if request.user == post.author %}
    <hr>
    <a href="{% url 'post_update' post.id %}">게시글 수정하기</a> 
    <a href="{% url 'post_delete' post.id %}">게시글 삭제하기</a>
    <br><br>
    {% endif %}
    <hr>
    <h4>댓글</h4>
    {% if user.is_authenticated %}
    <form method="POST" action="{% url 'create_comment' post.id %}"> 
        <!--제출 버튼을 누르면 create_comment라는 url로 이동, 그리고 어느 게시글인지 알려줘야 하니까 id도 같이 보냄-->
            {% csrf_token %}
            {{comment_form}}
            <input type="submit">
    </form>
    {% else %}
    로그인 후 사용해주세요!!
    {% endif %}
    <hr>
    <!-- 댓글 목록들 -->
    <!-- for문을 돌 때마다 blog_detail을 참조하고 있는 comment 객체들의 집합을 모조리 갖고와서 comment에 담아라 -->
    {% for comment in post.comment_set.all %}
    <p>{{ comment }}</p>
    <p>작성자: {{ comment.author }}</p>
    {% if request.user == comment.author %}
    <a href="{% url 'update_comment' post.id comment.id %}"> 수정 </a>
    <a href="{% url 'delete_comment' post.id comment.id %}"> 삭제 </a>
    {% endif %}
    <hr>
    {% endfor %}
</body>
</html>

blogProject/blog/templates/post_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h2>귀염둥이 동덕 멋사 블로그</h2>
    <!-- 수정된 코드 -->
    {% for post in posts %}
    <h3> <a href="{% url 'post_detail' post.id %}"> {{post.title}} </a></h3>
        작성자: {{post.author}}<br>
        {{post.body}}
        <hr>
    {% endfor %}   

    <!-- 페이지네이션 -->
    {% if posts.has_previous %} <!--지금 잘라서 보여주는 posts의 목록이 이전 페이지가 있다면-->
    <a href="?page=1">첫 페이지</a>
    <a href="?page={{posts.previous_page_number}}">이전 페이지</a> <!--posts의 이전 페이지 숫자를 반환해라-->
    {% endif %}

    <span> {{ posts.number }} </span> <!--현재 페이지 넘버-->
    <span> / </span>
    <span> {{ posts.paginator.num_pages }} </span> <!--잘린 posts가 갖고 있는 총 페이지 수 반환-->

    {% if posts.has_next %} <!--다음 페이지가 있다면-->
    <a href="?page={{posts.next_page_number}}">다음 페이지</a>
    <a href="?page={{posts.paginator.num_pages}}">마지막 페이지</a>
    {% endif %}
</body>
</html>